Blog_Project/Blog_App/urls.py
from django.urls import path
from . import views

app_name = 'Blog_App'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='create_blog'),
    path('details/<slug>', views.blog_details, name='blog_details'),
    path('liked/<pk>/', views.liked, name='liked_post'),
    path('unliked/<pk>/', views.unliked, name='unliked_post'),
    path('my-blogs/', views.MyBlogs.as_view(), name='my_blogs'),
    path('edit/<slug>/', views.UpdateBlog.as_view(), name='edit_blog'),

]

Blog_Project/Blog_Project/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views 
# for MEDIA
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('account/', include('Login_App.urls')),
    path('blog/', include('Blog_App.urls')),
    path('', views.Index, name='index' )
]

# FOR MEDIA
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Blog_Project/Blog_App/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.

class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    blog_title = models.CharField(max_length=264, verbose_name="Put a Title")
    slug = models.SlugField(max_length=264, unique=True)
    blog_content = RichTextField(blank=True, null=True)
    blog_image = models.ImageField(upload_to='blog_image', verbose_name='Image')
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-publish_date',]

    def __str__(self):
        return self.blog_title


class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_comment')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-comment_date',]


    def __str__(self):
        return self.comment


class Likes(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='liked_blog')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liked_user')

    def __str__(self):
        return self.user , " likes " , self.blog

Blog_Project/Blog_App/forms.py
from django import forms
from Blog_App.models import Blog, Comment

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('comment',)

Blog_Project/Blog_App/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import CreateView, UpdateView, ListView, DetailView, View, TemplateView, DeleteView
from Blog_App.models import Blog, Comment, Likes
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid #unique id generate
from Blog_App.forms import CommentForm
# Create your views here.

# def blog_list(request):
#     return render(request, 'Blog_App/blog_list.html', context={})

#BLOG LIST
class BlogList(ListView):
    context_object_name = 'blogs'
    model = Blog
    template_name = 'Blog_App/blog_list.html'
    # queryset = Blog.objects.order_by('-publish_date')

# BLOG CREATE
class CreateBlog(CreateView, LoginRequiredMixin):
    model = Blog
    template_name = 'Blog_App/create_blog.html'
    fields = ('blog_title', 'blog_content', 'blog_image')

    # non mentioned items generate
    def form_valid(self,form):
        blog_obj = form.save(commit=False)
        blog_obj.author = self.request.user
        title = blog_obj.blog_title
        blog_obj.slug = title.replace(' ', '-') + "-" + str(uuid.uuid4())
        blog_obj.save()
        return HttpResponseRedirect(reverse('index'))

#BLOG DETAILS
@login_required
def blog_details(request,slug):
    blog = Blog.objects.get(slug=slug)  #// my slug = published slug
    comment_form = CommentForm()
    already_liked = Likes.objects.filter(blog=blog, user=request.user)
    if already_liked:
        liked = True
    else:
        liked = False    
    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user #comment form user
            comment.blog = blog #this blog
            comment.save()
            return HttpResponseRedirect(reverse('Blog_App:blog_details', kwargs={'slug':slug} ))

    return render(request, 'Blog_App/blog_details.html', context={'blog':blog, 'comment_form':comment_form, 'liked':liked})



#LIKED
@login_required
def liked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=blog, user=user)
    if not already_liked:
        liked_post = Likes(blog=blog, user=user) #new object create
        liked_post.save()
    return HttpResponseRedirect(reverse('Blog_App:blog_details', kwargs={'slug':blog.slug} ))

#UNLIKED
@login_required
def unliked(request,pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=blog, user=user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('Blog_App:blog_details', kwargs={'slug':blog.slug} ))


#MY BLOGS
class MyBlogs(LoginRequiredMixin,TemplateView):
    # context_object_name= 'myblogs'
    template_name = "Blog_App/my_blogs.html"
    
class UpdateBlog(LoginRequiredMixin, UpdateView):
    model= Blog
    fields = ('blog_title', 'blog_content', 'blog_image')
    template_name= 'Blog_App/edit_blog.html'
    
    def get_success_url(self, **kwargs):
           return reverse_lazy('Blog_App:blog_details', kwargs={'slug':self.object.slug})

    

Blog_Project/templates/Blog_App/blog_details.html
{% extends 'base.html' %}
<!-- {% load custom_filters %} -->
{% load crispy_forms_tags %}
{% block title_block %} {{blog.blog_title}} {% endblock title_block %}
{% block body_block %}
    <div class="row">
        <div class="col-sm-6">
            <h2>{{blog.blog_title}}</h2>
            <h4>Posted By: @{{blog.author}}</h4>
            <h6><i>Published On: {{blog.publish_date}}</i></h6>
            <h6><i>Updated On: {{blog.update_date}}</i></h6>
            <h6><i>{{blog.liked_blog.count}} Likes | {{blog.blog_comment.count}} Comments</i></h6>
        </div>
        <div class="col-sm-6">
            <img src="/media/{{blog.blog_image}}" alt="" width="50%">
        </div>
        <p>
            {{blog.blog_content|safe}}
            <!-- {{blog.blog_content|striptags|linebreaks}} -->
        </p>
        <hr>
    </div>

        {% if not liked %}
        <a href="{% url 'Blog_App:liked_post' pk=blog.pk %}">
           <i class="fa-solid fa-thumbs-up fa-2x"></i>
        </a>
        {% else %}
        <a href="{% url 'Blog_App:unliked_post' pk=blog.pk %}">
            <i class="fa-solid fa-thumbs-down fa-2x"></i>
        </a>
        {% endif %}

    <div class="row">
        <div class="col-sm-6">
            <hr>
            <h5>Comments</h5>
            {% for comment in blog.blog_comment.all  %}
            <p><a href="#">@{{comment.user}}</a> {{comment.comment}} <br> <h6>{{comment.comment_date}}</h6>
            <hr>
            </p>
            {% endfor %}
        </div>
        <div class="col-sm-6">
            <form method="POST">
                {{comment_form|crispy}}
                {% csrf_token %}
                <button type="submit" class="btn btn-sm btn-primary">Comment</button>
            </form>
        </div>
    </div>




{% endblock body_block %}
        

Blog_Project/templates/Blog_App/blog_list.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title_block %} Blog List {% endblock %}
{% block body_block %}
<h1> List of blogs</h1>

{% for blog in blogs %}
<h3>{{ blog.blog_title }}</h3>
<h6><i>{{ blog.publish_date }}</i></h6>
<div class="row">
    <div class="col-sm-4">
        <img src="/media/{{blog.blog_image}}" alt="{{blog.blog_title}}" title="{{blog.blog_title}}" width="50%">
    </div>
    <div class="col-sm-8">
        <!-- <p>{{blog.blog_content|safe}}</p> <a href="{% url 'Blog_App:blog_details' slug=blog.slug %}">Read More</a> </p> -->
        <p>{{blog.blog_content|striptags|range_filter|linebreaks}} <a href="{% url 'Blog_App:blog_details' slug=blog.slug %}">Read More</a> </p>
        <h6>Posted By: <a href="#">@{{blog.author}}</a></h6>
        <h6><i>{{blog.liked_blog.count}} Likes | {{blog.blog_comment.count}} Comments</i></h6>
    </div>
</div>
<br>
<hr>
{% endfor %}




{% endblock %}
    
    

Blog_Project/templates/Blog_App/create_blog.html
{% extends 'base.html' %}


{% load crispy_forms_tags %}
{% block title_block %} Create Blog {% endblock title_block %}
{% block body_block %}
{% load static %}
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

<h2>Write Your Blog Here</h2>
<form action="" method="POST" enctype="multipart/form-data">
    {{ form|crispy }}
    {% csrf_token %}
    <br>
    <button type="submit" class="btn btn-success">Create Your Blog</button>
</form>












{% endblock body_block %}
        

Blog_Project/templates/Blog_App/edit_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{blog.blog_title}} {% endblock title_block %}
{% block body_block %}
{% if blog.author == user    %}   

<form method="POST">
{{form|crispy}}
{% csrf_token %}
<button type="submit" class="btn btn-sm btn-danger" > Update </button>
{% else %}
<p>You Are Not Allowed To View This Page. 404</p>
</form>
{% endif %}





{% endblock body_block %}
        

Blog_Project/templates/Blog_App/my_blogs.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title_block %} {{user}} {% endblock title_block %}
{% block body_block %}
    
{% for blog in user.post_author.all %}
<h3>{{blog.blog_title}}</h3>
<h6>{{blog.publish_date}}</h6>
<div class="row">
    <div class="col-sm-4">
        <img src="/media/{{blog.blog_image}}" width="50%" alt="{{blog.blog_title}}">
    </div>
    <div class="col-sm-8">
        <p>{{blog.blog_content|striptags|range_filter|linebreaks}} <a href="{% url 'Blog_App:blog_details' slug=blog.slug %}">Read More</a> </p>
    </div>
</div>
<div>
    <a href="{% url 'Blog_App:edit_blog' slug=blog.slug %}">EDIT</a>
</div>

<hr>

{% endfor %}



{% endblock body_block %}
        