Blog_Project/Blog_App/urls.py
from django.urls import path
from . import views

app_name = 'Blog_App'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='create_blog'),
    path('details/<slug>', views.blog_details, name='blog_details'),
    path('liked/<pk>/', views.liked, name='liked_post'),
    path('unliked/<pk>/', views.unliked, name='unliked_post'),
    path('my-blogs/', views.MyBlogs.as_view(), name='my_blogs'),
    path('edit/<slug>/', views.UpdateBlog.as_view(), name='edit_blog'),

]

Blog_Project/Blog_Project/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views 
# for MEDIA
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('account/', include('Login_App.urls')),
    path('blog/', include('Blog_App.urls')),
    path('', views.Index, name='index' )
]

# FOR MEDIA
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Blog_Project/Login_App/urls.py
from django.urls import path
from . import views

app_name = 'Login_App'


urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('signin/', views.sign_in, name='signin'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.user_profile, name='profile'),
    path('change/', views.user_change, name='change'),
    path('pass_change/', views.pass_change, name='pass_change'),
    path('add_picture/', views.add_pro_pic, name='add_picture'),
    path('picture_change/', views.change_picture, name='picture_change'),
]

Blog_Project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/e6fc29d63c.js" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

    <title>
        
        {% block title_block %}
            Blogs
        {% endblock %}
            
    </title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand m-2" href="#"><img src="/media/profile_image/LOGO2.png" alt="" width="30%"></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'index' %}">Home</a>
              </li>
              
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'Login_App:logout' %}">Log Out</a>
              </li> 
              <li class="nav-item">
                <a class="nav-link" href="{% url 'Login_App:profile' %}">My Profile</a>
              </li> 
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'Login_App:signup' %}">Sign Up</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'Login_App:signin' %}">Sign In</a>
              </li>
              {% endif %}    
              <li class="nav-item">
                <a class="nav-link" href="{% url 'Blog_App:my_blogs' %}">My Blogs</a>
              </li> 

              <li class="nav-item">
                <a class="nav-link" href="{% url 'Blog_App:create_blog' %}">Write Blog</a>
              </li>              
                 <hr>    
            </ul>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  @{{ user.username }}
                </a>
                {% if user.is_authenticated %}
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'Login_App:profile' %}">My Profile</a></li>
                  <li><a class="dropdown-item" href="{% url 'Login_App:logout' %}">Logoout</a></li>
                  {% else %}
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                </ul>
                {% endif %}
              </li>
          </div>
        </div>
      </nav>

     
      
        <div class="container" style="padding-top:20px">
          {% block body_block %}
        
        {% endblock %}
        </div>


</body>
</html>