Blog_Project/Blog_App/urls.py
from django.urls import path
from . import views

app_name = 'Blog_App'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='create_blog'),
    path('details/<slug>', views.blog_details, name='blog_details'),
    path('liked/<pk>/', views.liked, name='liked_post'),
    path('unliked/<pk>/', views.unliked, name='unliked_post'),
    path('my-blogs/', views.MyBlogs.as_view(), name='my_blogs'),
    path('edit/<slug>/', views.UpdateBlog.as_view(), name='edit_blog'),

]

Blog_Project/Blog_Project/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views 
# for MEDIA
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('account/', include('Login_App.urls')),
    path('blog/', include('Blog_App.urls')),
    path('', views.Index, name='index' )
]

# FOR MEDIA
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Blog_Project/Login_App/urls.py
from django.urls import path
from . import views

app_name = 'Login_App'


urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('signin/', views.sign_in, name='signin'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.user_profile, name='profile'),
    path('change/', views.user_change, name='change'),
    path('pass_change/', views.pass_change, name='pass_change'),
    path('add_picture/', views.add_pro_pic, name='add_picture'),
    path('picture_change/', views.change_picture, name='picture_change'),
]

Blog_Project/Login_App/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='user_profile', on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_image')

Blog_Project/Login_App/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from Login_App.models import UserProfile

# extra field add
class SignUpForm(UserCreationForm):

    email = forms.EmailField(label='Email Address' ,required=True)
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2') #default USer 


class UserProfileChange(UserChangeForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password')


class ProfilePic(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_pic',]
        

Blog_Project/Login_App/views.py
from django.shortcuts import render,HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login,authenticate,logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from Login_App.forms import SignUpForm, UserProfileChange, ProfilePic
# Create your views here.


# SIGN UP PAGE
def sign_up(request):
    form = SignUpForm() #default
    registered = False
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered = True

    dict = {'form':form, 'registered': registered}    
    return render(request, 'Login_App/signup.html', context=dict)   

# SIGN IN Page
def sign_in(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST) #all data pick
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            # user available or not?
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

    return render(request, 'Login_App/signin.html', context = {'form':form})     


# LOG OUT
@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

# user profile
@login_required
def user_profile(request):
    return render(request, 'Login_App/user_profile.html', context={})


# Update profile
@login_required
def user_change(request):
    current_user = request.user #user will save in current_user
    form = UserProfileChange(instance=current_user) # change value of current user
    if request.method == 'POST':
        form = UserProfileChange(request.POST, instance=current_user) 
        if form.is_valid():
            form.save()
            form = UserProfileChange(instance=current_user)

    return render(request, 'Login_App/change_profile.html', context={'form':form})        

# PASSWORD CHANGE
@login_required
def pass_change(request):
    current_user = request.user
    changed = False
    form = PasswordChangeForm(current_user)
    if request.method == 'POST':
        form = PasswordChangeForm(current_user, data=request.POST)
        if form.is_valid():
            form.save()
            changed=True
    return render(request, 'Login_App/change_pass.html', context={'form':form, 'changed':changed})        


@login_required
def add_pro_pic(request):
    form = ProfilePic()
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('Login_App:profile'))
    return render(request, 'Login_App/profile_pic_add.html', context={'form': form})

@login_required
def change_picture(request):
    form = ProfilePic(instance=request.user.user_profile)
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES, instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('Login_App:profile'))
    return render(request, 'Login_App/profile_pic_add.html', context={'form': form})

Blog_Project/templates/Login_App/change_pass.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
    Change Password
{% endblock title_block %}


{% block body_block %}
    <h2>Change Password</h2>
    {% if changed %}
    <div class="alert alert-success">Password changed successfully</div>
    {% endif %}
    <form  method="POST">
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Update</button>

    </form>





{% endblock body_block %}
    
    

Blog_Project/templates/Login_App/change_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
    Change Profile
{% endblock title_block %}


{% block body_block %}
   
<form  method="post">
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-warning">Change</button>
</form>





{% endblock body_block %}
    
    

Blog_Project/templates/Login_App/profile_pic_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
    Profile Pic Change
{% endblock title_block %}

{% block body_block %}
    <h2>Add Your Profile Picture</h2>
    <form method="POST" enctype="multipart/form-data">
        {{ form|crispy }}
        {% csrf_token %}
        <br>
        <button type="submit" class="btn btn-success btn-sm">Change Picture</button>
    </form>




{% endblock body_block %}
    
    

Blog_Project/templates/Login_App/signin.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Login {% endblock %}    


{% block body_block %}
    <h2>Sign In</h2>
    <form action="" method="POST">
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Sign In</button>
    </form>


{% endblock body_block %}
    
    

Blog_Project/templates/Login_App/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Create New Account {% endblock %}    
{% block body_block %}

{% if registered %}
<div class="alert alert-success">
    Account Created Successfully! <a href="{% url 'Login_App:signin' %}">LogIn Here</a>
</div>
{% else %}
<h2>Create New Account</h2>
<form  method="POST">
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-sm ">Create Account</button>
</form>
<br>
<p>Already Have An Account <a href="{% url 'Login_App:signin' %}">Login Here</a></p>

{% endif %}

{% endblock %}
    

Blog_Project/templates/Login_App/user_profile.html
{% extends 'base.html' %}

{% block title_block %}
    Profile
{% endblock title_block %}
{% block body_block %}
<!-- user_profile from model.py related name -->
<h2>Your Profile</h2>
{% if user.user_profile  %}
<img src="/media/{{user.user_profile.profile_pic}}" class="rounded-circle" width="100px" alt="">
<br><br>
<a href="{% url 'Login_App:picture_change' %}" class="btn btn-primary btn-sm">Change Profile Picture</a>
{% else %}

<img src="/media/profile_image/default.png" class="rounded-circle" width="150px" alt="">
<br><br>
<a href="{% url 'Login_App:add_picture' %}" class="btn btn-primary btn-sm">Change Profile Picture</a>
{% endif %}
<br> <br>
    <p>Username: {{ user.username }} </p>
    <p>Email: {{ user.email }} </p>
    <p>Name: {{ user.first_name }} {{ user.last_name }}</p>
    <br>
    <a href="{% url 'Login_App:change' %}" class="btn btn-info">Change Profile info</a>








{% endblock body_block %}
    
    